name: oracle
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  oktoast: ^3.4.0
  dio: ^5.4.1
  flutter_secure_storage: ^9.0.0
  get_it: ^8.0.2
  flutter_riverpod: ^2.4.10
  flutter_svg: ^2.0.10+1
  lottie: ^2.4.0
  hooks_riverpod: ^2.4.10
  awesome_dialog: ^3.1.0
  cached_network_image: ^3.3.1
  page_transition: ^2.1.0
  animations: ^2.0.11
  top_modal_sheet: ^2.1.0
  shared_preferences: ^2.3.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  slimy_card:
    git:
      url: /Users/immadominion/SlimyCard-Animated-Flutter-Package
  reown_appkit: ^1.2.0-beta01
  flutter_hooks:
    ^0.20.5
    # ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Int
      fonts:
        - asset: fonts/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
